# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
networks:
      dstar-net:
        external:
            name: dstar-net
version: '2'
volumes:
  orderer.dstar.com:
  peer0.org1.dstar.com:
  peer1.org1.dstar.com:

services:
  ca.dstar.com:
    container_name: ca.dstar.com
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.dstar.com 
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.dstar.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/89fdad2fc509809820994628a84eaf4586730c7ffbb945ecbddbe118567fdd10_sk
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dstar-net
    volumes:
      - ../crypto-config/peerOrganizations/org1.dstar.com/ca/:/etc/hyperledger/fabric-ca-server-config
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    networks:
      - dstar-net


  orderer.dstar.com:
    container_name: orderer.dstar.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      # - FABRIC_LOGGING_SPEC=debug
      # - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      # - ORDERER_GENERAL_LISTENPORT=7050
      # - ORDERER_GENERAL_GENESISMETHOD=file
      # - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      # - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      # - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      # - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dstar-net
      # - ORDERER_GENERAL_TLS_ENABLED=false
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dstar-net

      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=false
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/dstar.com/orderers/orderer.dstar.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/dstar.com/orderers/orderer.dstar.com/tls:/var/hyperledger/orderer/tls
      - orderer.dstar.com:/var/hyperledger/production/orderer
    #  - ../crypto-config/ordererOrganizations/dstar.com/orderers/orderer.dstar.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - dstar-net
  
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment: 
      - COUCHDB_USER= 
      - COUCHDB_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dstar-net
    ports:
      - 5984:5984
    networks:
      - dstar-net

  peer0.org1.dstar.com:
    container_name: peer0.org1.dstar.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB 
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984 
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME= 
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=

      - CORE_PEER_ID=peer0.org1.dstar.com
      - CORE_PEER_ADDRESS=peer0.org1.dstar.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.dstar.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.dstar.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.dstar.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dstar-net

    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.dstar.com/peers/peer0.org1.dstar.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.dstar.com/peers/peer0.org1.dstar.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.dstar.com:/var/hyperledger/production

    ports:
      - 7051:7051
    #  - 7053:7053
    depends_on: 
      - couchdb0
      - orderer.dstar.com
    networks:
      - dstar-net

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.dstar.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dstar.com/peers/peer0.org1.dstar.com/tls/server.crt
      - CORE_PEER_TLS_CLIENTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dstar.com/peers/peer0.org1.dstar.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dstar.com/peers/peer0.org1.dstar.com/tls/server.key
      - CORE_PEER_TLS_CLIENTKEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dstar.com/peers/peer0.org1.dstar.com/tls/server.key
      #- CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dstar.com/peers/peer0.org1.dstar.com/tls/ca.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/dstar.com/orderers/orderer.dstar.com/tls/ca.crt
 
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.dstar.com/users/Admin@org1.dstar.com/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dstar-net
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false

      #- ORDERER_CA = /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/dstar.com/orderers/orderer.dstar.com/msp/tlscacerts/tlsca.dstar.com-cert.pem

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    depends_on: 
      - orderer.dstar.com
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/github.com/chaincode
      - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - dstar-net

  peer1.org1.dstar.com:
    container_name: peer1.org1.dstar.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB 
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      
      - CORE_PEER_ID=peer1.org1.dstar.com
      - CORE_PEER_ADDRESS=peer1.org1.dstar.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.dstar.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.dstar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.dstar.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dstar-net

    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.dstar.com/peers/peer1.org1.dstar.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.dstar.com/peers/peer1.org1.dstar.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.dstar.com:/var/hyperledger/production
    ports:
      - 8051:8051
    #  - 7053:7053
    depends_on:
      - couchdb1
    networks:
      - dstar-net

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment: 
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dstar-net

    ports:
      - 6984:5984
    networks:
      - dstar-net